name: 'Setup EAS Build + Trigger Build'
description: 'Sets up Expo & EAS and triggers cloud build'

inputs:
  APP_ENV:
    description: 'APP_ENV (one of): development, staging, production'
    required: true
    default: staging
  ANDROID:
    description: 'Run for Android'
    required: false
    default: 'true'
  IOS:
    description: 'Run for iOS'
    required: false
    default: 'false'
  VERSION:
    description: 'Version label for build message'
    required: false
    default: '0.0.0'
  EXPO_TOKEN:
    description: 'Expo Token'
    required: true
    default: ''
  working-directory:
    description: 'Working directory'
    required: false
    default: 'apps/vnstock'

runs:
  using: composite
  steps:
    - name: 💯 Check for EXPO_TOKEN
      shell: bash
      run: |
        if [ -z "${{ inputs.EXPO_TOKEN }}" ]; then
          echo "❌ Missing EXPO_TOKEN. Please set the EXPO_TOKEN secret in repository settings."
          exit 1
        fi

    - name: 📦 Setup Expo and EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ inputs.EXPO_TOKEN }}

    - name: ⚙️ Run Prebuild
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm prebuild:${{ inputs.APP_ENV }}

    - name: 📱 Run Android Build
      if: ${{ inputs.ANDROID == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm build:${{ inputs.APP_ENV }}:android --non-interactive --no-wait --message "Build ${{ inputs.APP_ENV }} ${{ inputs.VERSION }}"

    - name: 📱 Run iOS Build
      if: ${{ inputs.IOS == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm build:${{ inputs.APP_ENV }}:ios --non-interactive --no-wait --message "Build ${{ inputs.APP_ENV }} ${{ inputs.VERSION }}"
