"""Gói mô hình dữ liệu chính cho hệ thống vnstock backend.

Được phân tách rõ ràng thành 2 phân hệ kiến trúc:
- app.models.entities: Các bảng cơ sở dữ liệu (Database Tables / SQLAlchemy ORM)
- app.models.dto: Các đối tượng truyền tải dữ liệu (Data Transfer Objects / Pydantic Schemas)

Đồng thời re-export toàn bộ tại đây để đảm bảo tính tương thích ngược 100%.
"""

from sqlmodel import SQLModel

from app.models.base import (
    VN_TZ,
    AwareSQLModel,
    JSONBVariant,
    get_datetime_utc,
    get_datetime_vn,
)
from app.models.dto import (
    CompanyOverviewPublic,
    EnsembleSignalRequest,
    EnsembleSignalResponse,
    EnsembleWeightsResponse,
    EnsembleWeightsUpdate,
    FinancialReportPublic,
    FinancialReportsResponse,
    FlowLiquidityEngineResponse,
    ForecastAggregateResponse,
    ForecastCreate,
    ForecastJournalPublic,
    ForecastResolve,
    ForecastScoredPublic,
    InstitutionalFlowPublic,
    ItemCreate,
    ItemPublic,
    ItemsPublic,
    ItemUpdate,
    MacroIndicatorPublic,
    MacroLatestResponse,
    MarkToMarketRequest,
    Message,
    NewPassword,
    OHLCVRecord,
    OrderCreateRequest,
    OrderResponse,
    PortfolioCreateRequest,
    PortfolioResponse,
    PortfoliosResponse,
    PositionCloseRequest,
    PositionResponse,
    PriceHistoryResponse,
    QuantMLEngineResponse,
    StockSymbolPublic,
    StockSymbolsPublic,
    SymbolGroupResponse,
    SyncStatusPublic,
    TechnicalEngineResponse,
    Token,
    TokenPayload,
    TradeResponse,
    UpdatePassword,
    UserCreate,
    UserPublic,
    UserRegister,
    UsersPublic,
    UserUpdate,
    UserUpdateMe,
    VnstockSymbolItem,
)
from app.models.entities import (
    CompanyProfile,
    DataSyncLog,
    FinancialReport,
    ForecastJournal,
    InstitutionalFlow,
    Item,
    ItemBase,
    MacroIndicator,
    MarketBreadth,
    Order,
    Portfolio,
    Position,
    StockOHLCVDaily,
    StockOHLCVIntraday,
    StockSymbol,
    TickFlowAggregated,
    Trade,
    User,
    UserBase,
    derivative_pnl,
    round_money,
)

__all__ = [
    # Base
    "AwareSQLModel",
    "JSONBVariant",
    "SQLModel",
    "VN_TZ",
    "derivative_pnl",
    "get_datetime_utc",
    "get_datetime_vn",
    "round_money",
    # Entities
    "CompanyProfile",
    "DataSyncLog",
    "FinancialReport",
    "ForecastJournal",
    "InstitutionalFlow",
    "Item",
    "ItemBase",
    "MacroIndicator",
    "MarketBreadth",
    "Order",
    "Portfolio",
    "Position",
    "StockOHLCVDaily",
    "StockOHLCVIntraday",
    "StockSymbol",
    "TickFlowAggregated",
    "Trade",
    "User",
    "UserBase",
    # DTOs
    "CompanyOverviewPublic",
    "EnsembleSignalRequest",
    "EnsembleSignalResponse",
    "EnsembleWeightsResponse",
    "EnsembleWeightsUpdate",
    "FinancialReportPublic",
    "FinancialReportsResponse",
    "FlowLiquidityEngineResponse",
    "ForecastAggregateResponse",
    "ForecastCreate",
    "ForecastJournalPublic",
    "ForecastResolve",
    "ForecastScoredPublic",
    "InstitutionalFlowPublic",
    "ItemCreate",
    "ItemPublic",
    "ItemUpdate",
    "ItemsPublic",
    "MacroIndicatorPublic",
    "MacroLatestResponse",
    "MarkToMarketRequest",
    "Message",
    "NewPassword",
    "OHLCVRecord",
    "OrderCreateRequest",
    "OrderResponse",
    "PortfolioCreateRequest",
    "PortfolioResponse",
    "PortfoliosResponse",
    "PositionCloseRequest",
    "PositionResponse",
    "PriceHistoryResponse",
    "QuantMLEngineResponse",
    "StockSymbolPublic",
    "StockSymbolsPublic",
    "SymbolGroupResponse",
    "SyncStatusPublic",
    "TechnicalEngineResponse",
    "Token",
    "TokenPayload",
    "TradeResponse",
    "UpdatePassword",
    "UserCreate",
    "UserPublic",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UsersPublic",
    "VnstockSymbolItem",
]
